package UsoCorreto.UsoPratico;

public interface Funcionario {
}


// INTERFACE DE MARCAÇÃO -> SERVEM PARA MARCAR  CLASSES,
// DE FORMA QUE AO REALIZAR OS INSTACEOF PODEMOS TESTAR UM CONJUNTO DE CLASSE.